### ISSUE TITLE
Allow for retrieving manifest from url

### ISSUE THREAD

**Issue by corneil** [fitzoh/maven-push-plugin#5]
It will be useful if the manifest can be retrieved from a URL instead of just a local file.

When using `cf maven-push` in a devops type script the manifest will probably be in some source or binary repo and initiating the push using just a url will simplify matters.

**Comment by shakuzen** [comment]
This enhancement sounds generally useful to the CF CLI; not just to this plugin. Have you checked if there is a request for this in CF CLI tracker already, or made one if there isn't one?

**Comment by corneil** [comment]
When invoking cf push you are likely to have a freshly built application at hand.
With `cf maven push` you will probably not because you want to retrieve from a repo. So the manifest may also be somewhere else.
Adding the code to check if manifest path starts with http: or https: doesn't  seem that involved. 

It may be a philosophical issue. The thinking being that something else is responsible for getting the manifest and app.

**Comment by shakuzen** [comment]
Those are good points. It makes a strong case for the functionality being desirable with this plugin. I do think it could be useful outside of this plugin as well, but I can raise that separately with the CLI team.

**Comment by fitzoh** [comment]
I'm a little worried about config getting messy (auth), but I should be able to take a stab at it this weekend.

**Comment by fitzoh** [comment]
Merged into the plugin repo with cloudfoundry/cli-plugin-repo#242 @corneil , lemme know if you get a chance to try it out
